function createaxes(Parent1, X1, Y1, X2, Y2,X3,Y3)
%CREATEAXES(Parent1, X1, Y1, X2, Y2)
%  PARENT1:  axes parent
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data

%  Auto-generated by MATLAB on 24-Feb-2019 00:12:57

% Create axes
axes1 = axes('Parent',Parent1);
hold(axes1,'on');

% Create plot
plot(X1,Y1);

% Create plot
plot(X2,Y2);

% Create plot
plot(X3,Y3);


set(gca,'YDir','reverse');
% Create ylabel
ylabel('y posistion');

% Create xlabel
xlabel('x posistion');


box(axes1,'on');