function createfigure(ZData1, YData1, XData1, CData1)
%CREATEFIGURE2(ZData1, YData1, XData1, CData1)
%  ZDATA1:  patch zdata
%  YDATA1:  patch ydata
%  XDATA1:  patch xdata
%  CDATA1:  patch cdata

%  Auto-generated by MATLAB on 11-Mar-2019 21:38:27

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);

% Create patch
patch('Parent',axes1,'ZData',ZData1,'YData',YData1,'XData',XData1,...
    'FaceColor','interp',...
    'EdgeColor','interp',...
    'CData',CData1);

set(gca,'YDir','reverse');
    
% Create zlabel
zlabel('time(s)');

% Create ylabel
ylabel('y posistion');

% Create xlabel
xlabel('x posistion');

% Create colorbar
colorbar('peer',axes1);
